[ETFE-2632] added ItemBulkPackagingChoice page
hmrc/emcs-tfe-create-movement-frontend pull request #169
Opened 2023-11-16 16:33 UTC by james-work-account

2023-11-17 15:11 UTC, LewisMitchell requested changes

2023-11-17 15:11 UTC, LewisMitchell commented on test/controllers/BaseNavigationControllerSpec.scala
> +  "validateIndexAsync" - {
Should this be done in the BaseItemNavControllerSpec instead? This remains unchanged?

2023-11-17 15:11 UTC, LewisMitchell commented on test/views/sections/items/ItemCommodityCodeViewSpec.scala
> +      val testEpc = "testEpcTobacco"
Does this need to change?
```suggestion
      val testEpc = testEpcTobacco
```

2023-11-17 15:11 UTC, LewisMitchell commented on test/views/sections/items/ItemCommodityCodeViewSpec.scala
> +        cnCode = "testCnCodeWine",
Does this need to change?
```suggestion
        cnCode = testCnCodeWine,
```

2023-11-17 15:11 UTC, LewisMitchell commented on test/controllers/sections/items/ItemBulkPackagingChoiceControllerSpec.scala
> +    "must redirect to the Index page for GET when no Item" in new Test(Some(emptyUserAnswers)) {
Is this testing where no EPC is in the user answers?

2023-11-17 15:11 UTC, LewisMitchell commented on test/controllers/sections/items/ItemBulkPackagingChoiceControllerSpec.scala
> +    "must redirect to the Index page for POST when no Item" in new Test(Some(emptyUserAnswers)) {
Is this testing where no EPC is in the user answers?

2023-11-17 15:11 UTC, LewisMitchell commented on test-utils/fixtures/messages/sections/items/ItemBulkPackagingChoiceMessages.scala
> +    val errorRequired: String => String = goodsType => s"Select yes if the $goodsType is being moved in bulk"
This isn't being used, should it be removed?

2023-11-17 15:11 UTC, LewisMitchell commented on test/navigation/ItemsNavigatorSpec.scala
> +      "must go from the ItemBulkPackagingChoicePage" - {
I think a test is missing for CAM-ITM24

2023-11-17 15:11 UTC, LewisMitchell commented on test/views/sections/items/ItemBulkPackagingChoiceViewSpec.scala
> +                Selectors.h2(1) -> messagesForLanguage.caption,
Is it worth adding a test for the caption?

2023-11-20 12:15 UTC, james-work-account commented on conf/messages
> +itemBulkPackagingChoice.error.required = Select yes if the {0} are being moved in bulk
I raised that as a problem with UCD, got the copydeck changed and then forgot to change the code 🫠 good spot

2023-11-20 14:30 UTC, LewisMitchell requested changes

2023-11-20 14:30 UTC, LewisMitchell commented on test/navigation/ItemsNavigatorSpec.scala
> +        "to the Packaging Select page" - {
Needs to change back

2023-11-20 14:30 UTC, LewisMitchell commented on test/navigation/ItemsNavigatorSpec.scala
> +        "to the Items Index page" - {
Needs to change

2023-11-20 14:43 UTC, LewisMitchell approved these changes

2023-11-20 14:44 UTC, merged