Refactor tests to remove reliance on applicationBuilder
hmrc/emcs-tfe-create-movement-frontend pull request #176
Opened 2023-11-20 12:12 UTC by james-work-account

2023-11-20 17:25 UTC, LewisMitchell requested changes
Reviewed app package

2023-11-20 17:25 UTC, LewisMitchell commented on app/controllers/sections/items/BaseItemsNavigationController.scala
> +  def withCnCodeInformation(idx: Index)(f: CnCodeInformation => Result)(implicit request: DataRequest[_]): Future[Result] = {
Could you add a test for this please?

2023-11-20 17:33 UTC, LewisMitchell commented on .g8/checkboxPage/generated-test/controllers/$className$ControllerSpec.scala
> +      val result = controller.onSubmit(testErn, testDraftId, NormalMode)(request.withFormUrlEncodedBody(("value", "answer")))
Was the form body wrong before?

2023-11-20 17:33 UTC, LewisMitchell commented on .g8/checkboxPage/generated-test/controllers/$className$ControllerSpec.scala
> +      emptyUserAnswers.set($className$Page, "answer")
Was the page answer wrong before?

2023-11-20 17:45 UTC, james-work-account commented on .g8/checkboxPage/generated-test/controllers/$className$ControllerSpec.scala
> +      val result = controller.onSubmit(testErn, testDraftId, NormalMode)(request.withFormUrlEncodedBody(("value", "answer")))
Nope, copy/paste error

2023-11-20 17:45 UTC, james-work-account commented on .g8/checkboxPage/generated-test/controllers/$className$ControllerSpec.scala
> +      emptyUserAnswers.set($className$Page, "answer")
Nope, copy/paste error

2023-11-21 07:22 UTC, LewisMitchell commented on .g8/checkboxPage/generated-test/controllers/$className$ControllerSpec.scala
> +      contentAsString(result) mustEqual view(form.fill("answer"), NormalMode)(dataRequest(request, userAnswers.get), messages).toString
This can be changed back in a later PR

2023-11-21 07:23 UTC, LewisMitchell approved these changes

2023-11-21 07:23 UTC, merged