[ETFE-1799] added code for error pages
hmrc/emcs-tfe-create-movement-frontend pull request #23
Opened 2023-09-13 15:36 UTC by james-work-account

- content update for error pages- WIP
- [ETFE-1799] bump dependencies
- [ETFE-1799] added code for error pages

2023-09-13 15:37 UTC, james-work-account commented
Related PR: https://github.com/hmrc/outage-pages/pull/1508

2023-09-14 05:22 UTC, grahampaulcook commented on conf/messages.en
> +timeout.message = For security reasons, you will be signed out in
The copy-deck has the content `For your security, we will sign you out in` (https://docs.google.com/spreadsheets/d/1og4lluJ0o75kvX5j2Ma_W54eUf_OAl6Ud8EfMYP14zI/edit?pli=1#gid=868164043)

2023-09-14 05:24 UTC, grahampaulcook requested changes
When timing out the application is redirecting to give feedback page rather than showing the applications timeout url with content from https://docs.google.com/spreadsheets/d/1og4lluJ0o75kvX5j2Ma_W54eUf_OAl6Ud8EfMYP14zI/edit?pli=1#gid=868164043

2023-09-14 15:16 UTC, grahampaulcook approved these changes

2023-09-14 15:47 UTC, merged