[ETFE-3498] - Added handling for degrees plato in error (704)
hmrc/emcs-tfe-create-movement-frontend pull request #266
Opened 2024-03-13 10:13 UTC by LewisMitchell

Raising as draft as it needs refactoring

Added in some missing tests on SAD and handling where a user navigates to declaration manually but they haven't fixed all submission failures

2024-03-13 16:01 UTC, LewisMitchell commented
Scenarios fixed in this PR:
- when a user has 1 error for item 1, and 2 errors for item 2, before if they removed item 1, only 1 of the 2 errors for item 2 would be reindexed
- when 2 items are in error, and the first item is changed (EPC code) it  would reindex all other items, however it should just remove the errors for that item and not touch any others

2024-03-13 16:06 UTC, LewisMitchell commented on app/utils/SubmissionFailureErrorCodes.scala
> +    override val code = "4402"
```suggestion
    override val code = itemQuantityError
```

2024-03-13 16:06 UTC, LewisMitchell commented on app/utils/SubmissionFailureErrorCodes.scala
> +    override val code = "4451"
```suggestion
    override val code = itemDegreesPlatoError
```

2024-03-14 16:52 UTC, james-work-account requested changes
Some of the files are a little strangely formatted, could you run an auto-format on the (non-view) files you've touched please?

Otherwise LGTM

2024-03-15 15:00 UTC, james-work-account approved these changes

2024-03-15 15:09 UTC, merged