[ETFE-2165] added the DestinationBusinessName controller/route/view
hmrc/emcs-tfe-create-movement-frontend pull request #71
Opened 2023-10-09 20:49 UTC by LadonJackson

2023-10-09 22:04 UTC, r-melvin approved these changes

2023-10-09 22:05 UTC, r-melvin submitted a review, later dismissed

2023-10-10 13:06 UTC, james-work-account requested changes

2023-10-10 13:06 UTC, james-work-account commented on app/views/sections/destination/DestinationBusinessNameView.scala.html
> +                label = LabelViewModel(HtmlContent(heading))
```suggestion
                label = LabelViewModel(Text(messages("destinationBusinessName.heading"))).asPageHeading(LabelSize.Large)
```

2023-10-10 13:06 UTC, james-work-account commented on app/views/sections/destination/DestinationBusinessNameView.scala.html
> +
```suggestion

@h2(messages("section.destination"), "govuk-caption-xl")
```
(it'd be better if this is `destination.subHeading` to align with the others but that's just a nitpick, not a priority)

2023-10-10 13:06 UTC, james-work-account commented on app/views/sections/destination/DestinationBusinessNameView.scala.html
> +    h1: components.h1,
```suggestion
    h1: components.h1,
    h2: components.h2,
```

2023-10-10 13:06 UTC, james-work-account commented on app/views/sections/destination/DestinationBusinessNameView.scala.html
> +
```suggestion
@import viewmodels.LabelSize

```

2023-10-10 13:06 UTC, james-work-account commented on app/views/sections/destination/DestinationBusinessNameView.scala.html
> +}
```suggestion
@{
    //$COVERAGE-OFF$
}
```

2023-10-10 13:56 UTC, james-work-account approved these changes

2023-10-12 13:56 UTC, r-melvin approved these changes

2023-10-12 14:51 UTC, merged