[ETFE-withAnswer] updated withAnswer to include optional redirectRoute parameter
hmrc/emcs-tfe-create-movement-frontend pull request #92
Opened 2023-10-18 12:38 UTC by james-work-account

2023-10-18 13:18 UTC, LewisMitchell reviewed
Could you rebase also? The JT's currently fail

2023-10-18 13:18 UTC, LewisMitchell commented on app/controllers/sections/transportArranger/TransportArrangerNameController.scala
> +      case transportArranger if transportArranger == GoodsOwner | transportArranger == Other => f(transportArranger)
A minor improvement if you want to make it 
```suggestion
      case transportArranger@(GoodsOwner | Other) => f(transportArranger)
```

2023-10-18 13:18 UTC, LewisMitchell commented on app/controllers/sections/transportArranger/TransportArrangerNameController.scala
> +      case transportArranger if transportArranger == GoodsOwner | transportArranger == Other => f(transportArranger)
(thanks Eric)

2023-10-18 17:52 UTC, james-work-account commented on app/controllers/sections/destination/DestinationDetailsChoiceController.scala
> +        withAnswer(DestinationTypePage) {
In my opinion, no - it's one of the very first pages in the CaM journey, ahead of the LRN screen. If they haven't even hit DestinationTypePage yet, they won't be able to do the rest of the journey and might as well start again.

2023-10-18 17:54 UTC, james-work-account commented on app/controllers/sections/destination/DestinationDetailsChoiceController.scala
> +        withAnswer(DestinationTypePage) {
If they're redirected to the DestinationTypePage, they might as well be starting again. We're intentionally not saving their user answers until after the INFO sub-section is complete for the first time, so if they don't have a DestinationTypePage, they haven't been through the INFO section for the first time, and are intentionally trying to get to a page which they shouldn't reach.

2023-10-23 09:46 UTC, LewisMitchell requested changes

2023-10-23 09:46 UTC, LewisMitchell commented on test/controllers/sections/transportUnit/TransportSealChoiceControllerSpec.scala
> +          controllers.sections.transportUnit.routes.TransportUnitIndexController.onPageLoad(testErn, testLrn).url
The test name says redirect to 'journey correction controller' I think this should be 'index controller'

2023-10-23 09:46 UTC, LewisMitchell commented on test/controllers/sections/transportUnit/TransportSealChoiceControllerSpec.scala
> +          controllers.sections.transportUnit.routes.TransportUnitIndexController.onPageLoad(testErn, testLrn).url
The test name says redirect to 'journey correction controller' I think this should be 'index controller'

2023-10-23 09:46 UTC, LewisMitchell commented on test/controllers/sections/guarantor/GuarantorVatControllerSpec.scala
> +          controllers.sections.guarantor.routes.GuarantorIndexController.onPageLoad(testErn, testLrn).url
The test name says redirect to 'arranger controller' I think this should be 'index controller'

2023-10-23 09:46 UTC, LewisMitchell commented on test/controllers/sections/guarantor/GuarantorVatControllerSpec.scala
> +          controllers.sections.guarantor.routes.GuarantorIndexController.onPageLoad(testErn, testLrn).url
The test name says redirect to 'arranger controller' I think this should be 'index controller'

2023-10-23 09:46 UTC, LewisMitchell commented on test/controllers/sections/guarantor/GuarantorNameControllerSpec.scala
> +          controllers.sections.guarantor.routes.GuarantorIndexController.onPageLoad(testErn, testLrn).url
The test name says redirect to 'arranger controller' I think this should be 'index controller'

2023-10-23 09:51 UTC, james-work-account commented on test/controllers/sections/guarantor/GuarantorNameControllerSpec.scala
> +        redirectLocation(result).value mustEqual controllers.routes.JourneyRecoveryController.onPageLoad().url
It does redirect to the journey recovery controller though? I think this test name is correct.

2023-10-23 09:51 UTC, LewisMitchell commented on test/controllers/sections/guarantor/GuarantorNameControllerSpec.scala
> +        redirectLocation(result).value mustEqual controllers.routes.JourneyRecoveryController.onPageLoad().url
Apologies, got carried away 🙈

2023-10-23 10:19 UTC, LewisMitchell approved these changes

2023-10-23 10:20 UTC, merged